name: test
mongo.url: mongodb://172.17.0.3
mongo.db: mongo-db-showplace-test1
mongo.collection: showplace


mongo:
    url: mongodb://172.17.0.3
    db: mongo-db-showplace-test1
    collection: showplace

logging:
    level:
        root: INFO
        cityguide: INFO
        org.springframework.web: INFO
